version: "3.7"

services:
  front:
    image: node:20
    ports: 
      - 3000:3000
    volumes:
      - ./front:/usr/src
    depends_on:
      - back
    command: bash -c "cd /usr/src && npm run dev"
    environment:
      - JWT_SECRET
      - OPENAI_API_KEI
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - NEXT_PUBLIC_BACK_IP
  back:
    image: node:20
    ports:
      - 8080:8080
    volumes:
      - ./back:/usr/src
    command: bash -c "cd /usr/src && npm run dev"
    depends_on:
      - mongo
  
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data:/data/db
    